export enum TypeKeys {
  MOVIES_FETCH = "MOVIES_FETCH",
  MOVIES_FETCH_FULFILLED = "MOVIES_FETCH_FULFILLED",
  MOVIES_FETCH_FAILED = "MOVIES_FETCH_FAILED",

  MOVIE_FETCH = "MOVIE_FETCH",
  MOVIE_FETCH_FULFILLED = "MOVIE_FETCH_FULFILLED",
  MOVIE_FETCH_FAILED = "MOVIE_FETCH_FAILED",
}