export enum TypeKeys {
  MOVIES_FETCH = "MOVIES_FETCH",
  MOVIES_FETCH_STOP = "MOVIES_FETCH_STOP",
  MOVIES_FETCH_FULFILLED = "MOVIES_FETCH_FULFILLED",
  MOVIES_FETCH_FAILED = "MOVIES_FETCH_FAILED",
}